version: "3.2"
services:
  redis:
    image: redis
    ports:
     - 6379:6379
  postgres:
    image: postgres
    ports: 
     - 5432:5432
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
  mariadb:
    image: mariadb
    ports: 
     - 3808:3808
    environment:
      MARIADB_DATABASE: "testdb"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "password"
      MARIADB_ROOT_PASSWORD: "password"
  mysql:
    image: mysql
    ports: 
     - 3306:3306
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
  db2:
    image: ibmcom/db2
    privileged: "true"
    ports:
     - 50000:50000
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "db2inst1"
      DB2INST1_PASSWORD: "password"
      DBNAME: "testdb"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "true"
      REPODB: "true"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "false"
      HADR_ENABLED: "false"
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04"
    ports:
     - 1433:1433
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"